### ISSUE TITLE
1.20.1 and Trinkets plz?

### ISSUE THREAD

**Issue by fulide** [KenRouKoro/InterconnectionPlayer#2]
有计划 向前支持吗 比如1.20.1
有计划 支持Trinkets模组吗

**Comment by KenRouKoro** [comment]
没有前向移植计划，因为neoforge和forge的二进制并不兼容。
Trinkets并没有多平台支持的意向，对它的支持计划优先级会较低，因为不可能在paper端兼容。

**Comment by fulide** [comment]
ok
